// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "get_post", input: string, result: Post | null } | 
        { key: "get_posts", input: never, result: Array<Post> } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "create_post", input: PostCreateInput, result: Post } | 
        { key: "delete_post", input: string, result: Post } | 
        { key: "update_post", input: PostUpdateInput, result: Post },
    subscriptions: never
};

export interface Post { id: string, title: string, content: string }

export interface PostCreateInput { title: string, content: string }

export interface PostUpdateInput { id: string, title: string | null, content: string | null }
